Repository openimsdk/tools, pull requests merged in 2024-07, with the labels that each got.

#95 feat: implement getthumbnail interface.
  s3/cont/controller.go
  s3/minio/minio.go
  s3/minio/thumbnail.go
  s3/s3.go
Labels: size/M

#96 add placeholder codes
  s3/cont/controller.go
  s3/cos/cos.go
  s3/kodo/kodo.go
  s3/oss/oss.go
Labels: size/M

#97 implement correct get thumbnail size
  s3/minio/minio.go
Labels: size/S

#98 fix uncorrect getObjectImageInfo implement.
  s3/minio/minio.go
Labels: size/XS

#99 add getResizeImageSize function in minio
  s3/minio/image.go
  s3/minio/minio.go
Labels: size/S

#100 refactor uncorrect getSIze implement.
  s3/minio/minio.go
Labels: size/XS

#101 update getResizeImageSize implement.
  s3/minio/image.go
  s3/minio/minio.go
Labels: size/S

#102 fix thumbnailResize implement.
  s3/minio/image.go
  s3/minio/minio.go
Labels: size/S

#103 fix uncorrect implement in ResizeImage.
  s3/minio/image.go
  s3/minio/minio.go
Labels: size/M

#104 fix: add log kv args in sql logger.
  log/sql_logger.go
Labels: size/XS

#105 refactor: update sqlLogger implement with have err args.
  log/sql_logger.go
Labels: size/S

#106 refactor: optimize error method implement in sqlLogger.
  log/sql_logger.go
Labels: size/S

#107 Fix log
  go.mod
  go.sum
  log/zap.go
Labels: size/L

#108 feature: slice sub
  utils/datautil/datautil.go
  utils/datautil/datautil_test.go
Labels: size/M

#109 feature: slice sub
  utils/datautil/datautil.go
Labels: size/S

#110 feature: slice sub
  utils/datautil/datautil.go
Labels: size/S

#111 fix log
  go.mod
  go.sum
  log/file-rotatelogs/LICENSE
  log/file-rotatelogs/README.md
  log/file-rotatelogs/event.go
  log/file-rotatelogs/example_test.go
  log/file-rotatelogs/interface.go
  log/file-rotatelogs/internal/fileutil/fileutil.go
  log/file-rotatelogs/internal/fileutil/fileutil_test.go
  log/file-rotatelogs/internal/option/option.go
  log/file-rotatelogs/options.go
  log/file-rotatelogs/rotatelogs.go
  log/file-rotatelogs/rotatelogs_test.go
  log/zap.go
Labels: size/XXL

#112 feat: implement rpc log format
  log/zap.go
Labels: size/S

#113 update middleware hijack.
  log/zap.go
  mw/rpc_client_interceptor.go
  mw/rpc_server_interceptor.go
Labels: size/M

#114 fix uncorrect index out.
  log/zap.go
Labels: size/XS

#115 feat: pic upload
  go.mod
  go.sum
  s3/minio/image.go
  s3/minio/thumbnail.go
Labels: size/M

#117 feat: slice copy
  utils/datautil/datautil.go
Labels: size/XS

#118 feat: CamelCaseToSpaceSeparated
  utils/stringutil/strings.go
  utils/stringutil/strings_test.go
Labels: size/S

#119 feat: change first
  utils/stringutil/strings.go
Labels: size/S
