Repository openimsdk/tools, pull requests merged in 2024-02, with the labels that each got.

#16 fix: fix the error output format
  component/component.go
Labels: size/S

#17 fix: fix the component return content
  component/component.go
  component/model.go
Labels: size/L

#18 feat: fix openim tools error code
  discoveryregistry/zookeeper/conf.go
  discoveryregistry/zookeeper/zk.go
Labels: size/M
