Repository openimsdk/tools, pull requests merged in 2024-03, with the labels that each got.

#19 fix: update the component check logic
  component/component.go
  mgoutil/mongo.go
Labels: size/L

#20 bugfix: fix internalserverError while connecting mongoDB with clustering uri
  tx/mongo.go
Labels: size/S

#21 refactor: separate functions with error containing message and error with only stack trace.
  a2r/api2rpc.go
  checker/check.go
  component/component.go
  discoveryregistry/zookeeper/conf.go
  discoveryregistry/zookeeper/discover.go
  discoveryregistry/zookeeper/zk.go
  errs/coderr.go
  mcontext/ctx.go
  mgoutil/mongo.go
  mw/gin.go
  mw/rpc_client_interceptor.go
  mw/rpc_server_interceptor.go
  tokenverify/jwt_token.go
Labels: size/L

#22 create code language detector file
  .github/code-language-detector.yml
  .github/workflows/code-language-detector.yml
Labels: size/S

#23 feat: add stdout and stderr info.
  log/zap.go
Labels: size/L

#25 feat: add copy function.
  go.mod
  utils/utils.go
Labels: size/XS

#27 feat: add strings function.
  utils/strings.go
Labels: size/L

#28 feat: add strings function.
  utils/strings.go
Labels: size/M

#30 fix: version update.
  log/zap.go
Labels: size/XS

#31 refactor: change go mod name.
  a2r/api2rpc.go
  apiresp/http.go
  apiresp/resp.go
  checker/check.go
  component/component.go
  discoveryregistry/zookeeper/conf.go
  discoveryregistry/zookeeper/discover.go
  discoveryregistry/zookeeper/log.go
  discoveryregistry/zookeeper/zk.go
  errs/coderr.go
  go.mod
  go.sum
  log/zap.go
  mcontext/ctx.go
  mgoutil/mongo.go
  mw/gin.go
  mw/rpc_client_interceptor.go
  mw/rpc_server_interceptor.go
  mw/specialerror/error.go
  network/ip.go
  tokenverify/jwt_token.go
Labels: size/M

#32 refactor: change go mod name.
  log/zap.go
  mcontext/ctx.go
Labels: size/M

#35 refactor: change log msg align.
  log/zap.go
Labels: size/XS

#36 docs: add redis config
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/auto-invite.yml
  .github/workflows/auto-tag.yml
  .github/workflows/bot-auto-cherry-pick.yml
  .github/workflows/bot-cherry-pick.yml
  .github/workflows/cla.yml
  .github/workflows/link-pr.yml
  .github/workflows/lock-issue.yml
  .github/workflows/milestone.yml
  .github/workflows/project-progress.yml
  .gitignore
  db/mysql/.keep
  errs/coderr.go
  redis/doc.go
  redis/init_redis.go
Labels: size/XXL

#43 test: test cicd make lint and make test
  README.md
Labels: size/XS

#42 add check_test.go file
  checker/check_test.go
Labels: size/M

#44 add some test file
  config/validation/validation_test.go
  discovery/discovery_register_test.go
  go.mod
  go.sum
  utils/idutil/id_generator_test.go
  version/version_test.go
Labels: size/L
