Repository openimsdk/tools, pull requests merged in 2024-12, with the labels that each got.

#165 fix: Add a lead time for the token's issuance time.
  tokenverify/jwt_token.go
Labels: size/XS

#166 feat: log add panic level.
  log/logger.go
  log/zap.go
  log/zap_test.go
Labels: size/M

#164 fix: update reqParams to support UTF-8
  s3/minio/minio.go
Labels: size/XS

#168 feat: add runtime env checker method.
  utils/runtimeenv/runtime.go
Labels: size/M

#169 fix: log loss method.
  discovery/zookeeper/log.go
Labels: size/XS

#170 feat: support aws and fix kodo
  go.mod
  go.sum
  s3/aws/aws.go
  s3/cont/controller.go
  s3/cos/cos.go
  s3/kodo/internal.go
  s3/kodo/kodo.go
  s3/minio/minio.go
  s3/oss/oss.go
Labels: size/XL

#171 feat: update k8s discovery.
  discovery/kubernetes/kubernetes.go
Labels: size/L

#172 fix: comment print in runtime Env.
  utils/runtimeenv/runtime.go
Labels: size/XS

#173 feat: ip && etcd
  discovery/etcd/etcd.go
  utils/network/ip.go
Labels: size/S

#174 feat: log.ZPanic
  errs/stack.go
  log/logger.go
  log/zap.go
  mw/errstack.go
  mw/gin.go
  mw/rpc_client_interceptor.go
Labels: size/L

#175 fix: zk log
  discovery/zookeeper/log.go
Labels: size/XS

#176 fix: improve discovery implement.
  discovery/kubernetes/kubernetes.go
Labels: size/M

#178 fix: improve error wrap.
  db/mongoutil/verify.go
  discovery/kubernetes/kubernetes.go
Labels: size/S

#179 feat: call rpc v2
  a2r/call_v2.go
Labels: size/M

#180 build: improve discovery Opts check
  discovery/etcd/etcd.go
  discovery/kubernetes/kubernetes.go
Labels: size/M

#181 fix: revert checkOpts.
  discovery/etcd/etcd.go
  discovery/kubernetes/kubernetes.go
Labels: size/M

#182 feat: call rpc v2
  a2r/call_v2.go
Labels: size/XS

#183 feat: Optimize minio's DeleteObject
  s3/minio/minio.go
Labels: size/M

#184 feat: adjust api call rpc
  a2r/api2rpc.go
  a2r/call_v2.go
  a2r/option.go
Labels: size/M

#185 feat: panic resp is success
  mw/rpc_server_interceptor.go
Labels: size/XS

#186 feat: optimize error
  discovery/etcd/etcd.go
  discovery/zookeeper/log.go
  errs/code.go
  errs/coderr.go
  errs/panic.go
  errs/predefine.go
  errs/stack.go
  errs/stack/stack.go
  go.mod
  log/file-rotatelogs/internal/fileutil/fileutil.go
  log/file-rotatelogs/rotatelogs.go
  log/file-rotatelogs/rotatelogs_test.go
  log/logger.go
  log/sql_logger.go
  log/zap.go
  mw/errstack.go
  mw/gin.go
  mw/rpc_client_interceptor.go
  mw/rpc_server_interceptor.go
  utils/stringutil/strings.go
Labels: size/L

#187 feat: add intersection func.
  utils/datautil/datautil.go
Labels: size/M

#188 feat: optimize log out
  go.mod
  log/zap.go
  mw/rpc_client_interceptor.go
  mw/rpc_server_interceptor.go
Labels: size/L
