Repository openimsdk/tools, pull requests merged in 2025-06, with the labels that each got.

#212 fix: get Key with prefix
  discovery/discovery_register.go
  discovery/etcd/etcd.go
  discovery/kubernetes/kubernetes.go
  discovery/standalone/kv.go
  discovery/zookeeper/zk.go
Labels: size/S

#213 fix: k8s discovery
  discovery/kubernetes/kubernetes.go
Labels: size/M

#214 feat: support redis sentinel mode.
  db/redisutil/redis.go
Labels: size/M

#216 fix: k8s discovery
  discovery/kubernetes/kubernetes.go
Labels: size/XS

#218 Feat/redis mode
  db/redisutil/redis.go
Labels: size/M

#220 feat: support mongo replicaset.
  db/mongoutil/mongo.go
Labels: size/L

#221 fix: update correct tags.
  db/mongoutil/mongo.go
  db/redisutil/redis.go
Labels: size/M
